plugins { id 'com.android.application' }

android {
    namespace 'com.gapgpt.fastdeskbrowser'
    compileSdk 35
    defaultConfig {
        applicationId 'com.gapgpt.fastdeskbrowser'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '1.0.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}


dependencies {
    implementation 'androidx.core:core:1.15.0'
}
